#!/bin/bash

# tree traversal
# GNU Affero General Public License v3.0

main() {
  clear;
  echo -e "\n\n\n";
  ls --color
  echo -e "\n";
  read -p "seek: " seek_item;
  if [[ "$@" = *-c* ]]
  then
    read -p "command: " command_name;
  else
    alias command_name=''
  fi
  echo -e "\n";
  if [[ "$@" = *-f* ]] 
  then
    if [[ $PWD = '/' ]]
    then
      if [[ "$command_name" = '' ]]
      then
	sudo find ./ -name "*$seek_item*" -print -quit;
      else
	sudo find ./ -name "*$seek_item*" -execdir "$command_name" "{}" +;
      fi
    else
      if [[ "$command_name" = '' ]]
      then
	find ./ -name "*$seek_item*" -print -quit;
      else
	find ./ -name "*$seek_item*" -execdir "$command_name" "{}" +;
      fi
    fi
  elif [[ "$@" != *-f* ]]
  then
    if [[ $PWD = '/' ]]
    then
      if [[ "$command_name" = '' ]]
      then
	sudo find ./ -name "*$seek_item*";
      else
	sudo find ./ -name "*$seek_item*" -execdir "$command_name" "{}" +;
      fi
    else
      if [[ "$command_name" = '' ]]
      then
	find ./ -name "*$seek_item*";
      else
	find ./ -name "*$seek_item*" -execdir "$command_name" "{}" +;
      fi
    fi
  fi
  echo -e "\n\n\n";
}

main "$@"

