#!/bin/bash

# site init
# GNU Affero General Public License v3.0

main() {
  clear;
  echo -e "\n\n\n";
  ls --color
  echo -e "\n";
  read -p "seek: " seek_item;
  read -p "command: " command_name;
  echo -e "\n";
  if [[ $PWD = '/' ]]
  then
    if [[ $command_name = '' ]]
    then
      sudo find ./ -name "*$seek_item*";
    else
      sudo find ./ -name "*$seek_item*" -exec "$command_name" {} \;
    fi
  else
    if [[ $command_name = '' ]]
    then
      find ./ -name "*$seek_item*";
    else
      find ./ -name "*$seek_item*" -exec "$command_name" {} \;
    fi
  fi
  echo -e "\n\n\n";
}

main
